#include "gpio.h"

void GPIO_PWMLed1_Init(void) {
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    GPIOA->MODER &= ~GPIO_MODER_MODER0;
    GPIOA->MODER |= GPIO_MODER_MODER0_1;

    GPIOA->AFR[0] |= (2 << GPIO_AFRL_AFRL0_Pos);

    GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0;
}

void GPIO_PWMLed2_Init(void) {
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    GPIOA->MODER &= ~GPIO_MODER_MODER3;
    GPIOA->MODER |= GPIO_MODER_MODER3_1;

    GPIOA->AFR[0] |= (2 << GPIO_AFRL_AFRL3_Pos);

    GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR3;
}

void GPIO_PWMLed3_Init(void) {
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;

    GPIOE->MODER &= ~GPIO_MODER_MODER9;
    GPIOE->MODER |= GPIO_MODER_MODER9_1;

    GPIOE->AFR[1] |= (1 << GPIO_AFRH_AFRH1_Pos);

    GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9;
}

void GPIO_PWMLed4_Init(void) {
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;

    GPIOE->MODER &= ~GPIO_MODER_MODER11;
    GPIOE->MODER |= GPIO_MODER_MODER11_1;

    GPIOE->AFR[1] |= (1 << GPIO_AFRH_AFRH3_Pos);

    GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR11;
}
